name = "yetanotherclown/token_bucket"
version = "0.1.0"
description = "A Token Bucket implementation for Luau"
authors = ["YetAnotherClown"]
repository = "https://www.github.com/YetAnotherClown/token-bucket-luau"
license = "MIT"

includes = ["pesde.toml", "pesde.lock", "README.md", "LICENSE.md", "src", "src/**"]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"